POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "What's new with NestJS",
    "postType": "post",
    "slug": "new-with-nestjs",
    "status": "draft",
    "content": "test content",
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "featuredImageUrl": "http://localhost:3000/images/image1.png",
    "publishedOn": "2026-08-02T14:30:00+05:30",
    "tags": ["nestjs", "typescript"]
}