POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "What's new with NestJS",
    "postType": "post",
    "slug": "new-with-nestjs",
    "status": "draft",
    "content": "test content",
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "featuredImageUrl": "https://localhost.com/images/image_one.png",
    "publishOn": "2018-08-18T00:00:00+10",
    "tags": ["nestjs", "typescript"],
    "metaOptions": [
        {
            "key": "testKey",
            "value": 20
        }
    ]
}