POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "What's new with NestJS",
    "postType": "post",
    "slug": "new-with-nestjs-7",
    "status": "draft",
    "content": "test content",
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "featuredImageUrl": "https://localhost.com/images/image_one.png",
    "publishOn": "2026-08-20T16:40:00Z",
    //"tags": ["nestjs", "typescript"],
    "metaOptions": 
        {
            "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
        },
    "authorId": 2
    
}